site_name: Wayfire Wiki
docs_dir: docs

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tracking
    - navigation.expand

  palette:
    - scheme: slate
      primary: blue
      accent: light blue

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - General: General.md
  - Configuration: Configuration.md
  - Tutorial: Tutorial.md
  - Contributing: Contributing.md
  - 'Tips & Tricks': 'Tips-&-Tricks.md'
  - FAQ: FAQ.md
  - For Developers:
    - 'IPC for developers': IPC-for-developers.md
    - 'Plugin architecture': Plugin-architecture.md
    - 'View life cycle': View-life-cycle.md
    - 'Views, Toplevels and Transactions': Views,-Toplevels-and-Transactions.md
    - 'Scenegraph': Scenegraph.md
    - 'Rendering': Rendering.md
    - '[WIP] Design overview': '[WIP]-Design-overview.md'
    - '[WIP] What does a compositor do?': '[WIP]-What-does-a-compositor-do?.md'
  - Advanced Topics:
    - 'Bindings available by default': Bindings-available-by-default.md
    - 'Debugging problems': Debugging-problems.md
    - 'Additional configuration for external applications': Additional-configuration-for-external-applications.md
    - 'Localisation': Localisation.md
    - 'Project goals': Project-goals.md
    - 'Related projects': Related-projects.md
